---
# Source: workbench/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-workbench
  labels:
    helm.sh/chart: workbench-0.1.0
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: workbench
    app.kubernetes.io/instance: local
    workbench.j4ns8i.github.com/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      workbench.j4ns8i.github.com/component: api
  template:
    metadata:
      labels:
        helm.sh/chart: workbench-0.1.0
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: workbench
        app.kubernetes.io/instance: local
        workbench.j4ns8i.github.com/component: api
    spec:
      serviceAccountName: local-workbench
      containers:
        - name: "api"
          image: "workbench/api:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
