apiVersion: v1
kind: Service
metadata:
  name: {{ include "workbench.fullname" . }}
  labels:
    {{- include "workbench.apiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "workbench.apiSelectorLabels" . | nindent 4 }}
